{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "11 exception handling\n",
    "What to Do When\n",
    "Things Go Wrong\n",
    "I’ve tested this rope to\n",
    "destruction...what can\n",
    "possibly go wrong?\n",
    "Things go wrong, all the time—no matter how good your code is. \u0003\n",
    "You’ve successfully executed all of the examples in this book, and you’re likely confident all\n",
    "of the code presented thus far works. But does this mean the code is robust? Probably not.\n",
    "Writing code based on the assumption that nothing bad ever happens is (at best) naive. At\n",
    "worst, it’s dangerous, as unforeseen things do (and will) happen. It’s much better if you’re\n",
    "wary while coding, as opposed to trusting. Care is needed to ensure your code does what\n",
    "you want it to, as well as reacts properly when things go south. In this chapter, you’ll not only\n",
    "see what can go wrong, but also learn what to do when (and, oftentimes, before) things do.\n",
    "this is a new chapter   413"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "for issues\n",
    "We’re starting this chapter by diving right in. Presented below is the latest code to the\n",
    "vsearch4web.py webapp. As you’ll see, we’ve updated this code to use the check_\n",
    "logged_in decorator from the last chapter to control when the information presented by the\n",
    "/viewlog URL is (and isn’t) visible to users.\n",
    "Take as long as you need to read this code, then use a pencil to circle and annotate the parts\n",
    "you think might cause problems when operating within a production environment. Highlight\n",
    "everything that you think might cause an issue, not just potential runtime issues or errors.\n",
    "from flask import Flask, render_template, request, escape, session\n",
    "from vsearch import search4letters\n",
    "from DBcm import UseDatabase\n",
    "from checker import check_logged_in\n",
    "app = Flask(__name__)\n",
    "app.config['dbconfig'] = {'host': '127.0.0.1',\n",
    "'user': 'vsearch',\n",
    "'password': 'vsearchpasswd',\n",
    "'database': 'vsearchlogDB', }\n",
    "@app.route('/login')\n",
    "def do_login() -> str:\n",
    "session['logged_in'] = True\n",
    "return 'You are now logged in.'\n",
    "@app.route('/logout')\n",
    "def do_logout() -> str:\n",
    "session.pop('logged_in')\n",
    "return 'You are now logged out.'\n",
    "def log_request(req: 'flask_request', res: str) -> None:\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "_SQL = \"\"\"insert into log\n",
    "(phrase, letters, ip, browser_string, results)\n",
    "values\n",
    "(%s, %s, %s, %s, %s)\"\"\"\n",
    "cursor.execute(_SQL, (req.form['phrase'],\n",
    "req.form['letters'],\n",
    "req.remote_addr,\n",
    "req.user_agent.browser,\n",
    "res, ))\n",
    "414   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.route('/search4', methods=['POST'])\n",
    "def do_search() -> 'html':\n",
    "phrase = request.form['phrase']\n",
    "letters = request.form['letters']\n",
    "title = 'Here are your results:'\n",
    "results = str(search4letters(phrase, letters))\n",
    "log_request(request, results)\n",
    "return render_template('results.html',\n",
    "the_title=title,\n",
    "the_phrase=phrase,\n",
    "the_letters=letters,\n",
    "the_results=results,)\n",
    "@app.route('/')\n",
    "@app.route('/entry')\n",
    "def entry_page() -> 'html':\n",
    "return render_template('entry.html',\n",
    "the_title='Welcome to search4letters on the web!')\n",
    "@app.route('/viewlog')\n",
    "@check_logged_in\n",
    "def view_the_log() -> 'html':\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "_SQL = \"\"\"select phrase, letters, ip, browser_string, results\n",
    "from log\"\"\"\n",
    "cursor.execute(_SQL)\n",
    "contents = cursor.fetchall()\n",
    "titles = ('Phrase', 'Letters', 'Remote_addr', 'User_agent', 'Results')\n",
    "return render_template('viewlog.html',\n",
    "the_title='View Log',\n",
    "the_row_titles=titles,\n",
    "the_data=contents,)\n",
    "app.secret_key = 'YouWillNeverGuessMySecretKey'\n",
    "if __name__ == '__main__':\n",
    "app.run(debug=True)\n",
    "you are here 4   415"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ng issues\n",
    "You were to take as long as you needed to read the code shown below (which is an updated\n",
    "version of the vsearch4web.py webapp). Then, using a pencil, you were to circle and\n",
    "annotate the parts you thought might cause problems when operating within a production\n",
    "environment. You were to highlight everything you thought might cause an issue, not just\n",
    "potential runtime issues or errors. (We’ve numbered our annotations for ease of reference.)\n",
    "from flask import Flask, render_template, request, escape, session\n",
    "from vsearch import search4letters\n",
    "from DBcm import UseDatabase\n",
    "from checker import check_logged_in\n",
    "app = Flask(__name__)\n",
    "2. Are these SQL statements\n",
    "protected from nasty web-base\n",
    "attacks such as SQL injection or d\n",
    "Cross-site scripting?\n",
    "app.config['dbconfig'] = {'host': '127.0.0.1',\n",
    "'user': 'vsearch',\n",
    "1. What happens\n",
    "'password': 'vsearchpasswd',\n",
    "if the database\n",
    "'database': 'vsearchlogDB', }\n",
    "connection fails?\n",
    "@app.route('/login')\n",
    "def do_login() -> str:\n",
    "session['logged_in'] = True\n",
    "return 'You are now logged in.'\n",
    "@app.route('/logout')\n",
    "def do_logout() -> str:\n",
    "session.pop('logged_in')\n",
    "return 'You are now logged out.'\n",
    "executing\n",
    "3. What happens if ents takes\n",
    "these SQL statem\n",
    "a long time?\n",
    "def log_request(req: 'flask_request', res: str) -> None:\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "_SQL = \"\"\"insert into log\n",
    "(phrase, letters, ip, browser_string, results)\n",
    "values\n",
    "(%s, %s, %s, %s, %s)\"\"\"\n",
    "cursor.execute(_SQL, (req.form['phrase'],\n",
    "req.form['letters'],\n",
    "req.remote_addr,\n",
    "req.user_agent.browser,\n",
    "res, ))\n",
    "416   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "@app.route('/search4', methods=['POST'])\n",
    "def do_search() -> 'html':\n",
    "phrase = request.form['phrase']\n",
    "letters = request.form['letters']\n",
    "title = 'Here are your results:'\n",
    "results = str(search4letters(phrase, letters))\n",
    "log_request(request, results)\n",
    "return render_template('results.html',\n",
    "the_title=title,\n",
    "the_phrase=phrase,\n",
    "the_letters=letters,\n",
    "the_results=results,)\n",
    "4. What happens\n",
    "if this call fails?\n",
    "@app.route('/')\n",
    "@app.route('/entry')\n",
    "def entry_page() -> 'html':\n",
    "return render_template('entry.html',\n",
    "the_title='Welcome to search4letters on the web!')\n",
    "@app.route('/viewlog')\n",
    "@check_logged_in\n",
    "def view_the_log() -> 'html':\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "_SQL = \"\"\"select phrase, letters, ip, browser_string, results\n",
    "from log\"\"\"\n",
    "cursor.execute(_SQL)\n",
    "contents = cursor.fetchall()\n",
    "titles = ('Phrase', 'Letters', 'Remote_addr', 'User_agent', 'Results')\n",
    "return render_template('viewlog.html',\n",
    "the_title='View Log',\n",
    "the_row_titles=titles,\n",
    "the_data=contents,)\n",
    "app.secret_key = 'YouWillNeverGuessMySecretKey'\n",
    "if __name__ == '__main__':\n",
    "app.run(debug=True)\n",
    "you are here 4   417"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Databases Aren’t Always Available\n",
    "We’ve identified four potential issues with the vsearch4web.py code, and we\n",
    "concede that there may be many more, but we’ll worry about these four issues for now.\n",
    "Let’s consider each of the four issues in more detail (which we do here and on the next\n",
    "few pages, by simply describing the problems; we’ll work on solutions later in this chapter).\n",
    "First up is worrying about the backend database:\n",
    "1\n",
    "What happens if the database connection fails?\n",
    "Our webapp blissfully assumes that the backend database is always\n",
    "operational and available, but it may not be (for any number of reasons).\n",
    "At the moment, it is unclear what happens when the database is down,\n",
    "as our code does not consider this eventuality.\n",
    "Let’s see what happens if we temporarily switch off the backend database. As you can\n",
    "see below, our webapp loads fine, but as soon as we do anything, an intimidating error\n",
    "message appears:\n",
    "Everything\n",
    "looks OK\n",
    "here...\n",
    "...but, when you click\n",
    "on the “Do it!” button,\n",
    "the webapp crashes with\n",
    "an “InterfaceError”.\n",
    "418   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Web At tacks Are a Re al Pain\n",
    "As well as worrying about issues with your backend database, you also need to\n",
    "worry about nasty individuals trying to do nasty things to your webapp, which\n",
    "brings us to the second issue:\n",
    "2\n",
    "Is our webapp protected from web attacks?\n",
    "The phrases SQL injection (SQLi) and Cross-site scripting (XSS) should\n",
    "strike fear in the heart of every web developer. The former allows\n",
    "attackers to exploit your backend database, while the latter allows them\n",
    "to exploit your website. There are other web exploits that you’ll need to\n",
    "worry about, but these are the “big two.”\n",
    "As with the first issue, let’s see what happens when we try to simulate these exploits\n",
    "against our webapp. As you can see, it appears we’re ready for both of them:\n",
    "If you try to inject SQL int\n",
    "the web interface, it has no o\n",
    "effect (other than the exp\n",
    "“search4letters” output). ected\n",
    "pt\n",
    "Any attempt to exploit XSS by feeding JavaScri\n",
    "ct.\n",
    "effe\n",
    "to the webapp has no\n",
    "The JavaScript isn’t executed (th\n",
    "treated just like any other textua ankfully); it’s\n",
    "l data sent to the\n",
    "webapp.\n",
    "you are here 4   419"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Input-Output Is (Some times) Slow\n",
    "At the moment, our webapp communicates with our backend database in an\n",
    "almost instantaneous manner, and users of our webapp notice little or no delay as\n",
    "the webapp interacts with the database. But imagine if the interactions with the\n",
    "backend database took some time, perhaps seconds:\n",
    "3\n",
    "What happens if something takes a long time?\n",
    "Perhaps the backend database is on another machine, in another\n",
    "building, on another continent...what would happen then?\n",
    "Communications with the backend database may take time. In fact, whenever\n",
    "your code has to interact with something that’s external to it (for example: a file, a\n",
    "database, a network, or whatever), the interaction can take any amount of time,\n",
    "the determination of which is usually beyond your control. Despite this lack of\n",
    "control, you do have to be cognizant that some operations may be lengthy.\n",
    "To demonstrate this issue, let’s add an artificial delay to our webapp (using the\n",
    "sleep function, which is part of the standard library’s time module). Add this\n",
    "line of code to the top of your webapp (near the other import statements):\n",
    "from time import sleep\n",
    "With the above import statement inserted, edit the log_request function\n",
    "and insert this line of code before the with statement:\n",
    "sleep(15)\n",
    "If you restart your webapp, then initiate a search, there’s a very distinct delay\n",
    "while your web browser waits for your webapp to catch up. As web delays go, 15\n",
    "seconds will feel like a lifetime, which will prompt most users of your webapp to\n",
    "believe something has crashed:\n",
    "o\n",
    "After clicking on the “D\n",
    "b\n",
    "it!” button, your we its...\n",
    "browser waits...and wa ...\n",
    "and waits...and waits\n",
    "420   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Your Function Calls Can Fail\n",
    "The final issue identified during this chapter’s opening exercise relates to the\n",
    "function call to log_request within the do_search function:\n",
    "4\n",
    "What happens if a function call fails?\n",
    "There’s never a guarantee that a function call will succeed, especially if\n",
    "the function in question interacts with something external to your code.\n",
    "We’ve already seen what can happen when the backend database is unavailable—\n",
    "the webapp crashes with an InterfaceError:\n",
    "There’s no\n",
    "database, so\n",
    "your webapp\n",
    "crashes.\n",
    "Other problems can surface, too. To simulate another error, find the sleep(15)\n",
    "line you added from the Issue 3 discussion, and replace it with a single statement:\n",
    "raise. When executed by the interpreter, raise forces a runtime error. If you\n",
    "try your webapp again, a different error occurs this time:\n",
    "Something\n",
    "else went\n",
    "wrong, and\n",
    "your webapp\n",
    "crashes again.\n",
    "Before flipping the\n",
    "page, remove that\n",
    "call to “raise” from\n",
    "your code to ensure\n",
    "the webapp starts\n",
    "working again.\n",
    "you are here 4   421"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Considering the Identified Problems\n",
    "We’ve identified four issues with the vsearch4web.py code. Let’s revisit each\n",
    "and consider our next steps.\n",
    "1. Your database connection fails\n",
    "Errors occur whenever an external system your code relies on is unavailable. The\n",
    "interpreter reported an InterfaceError when this happened. It’s possible to\n",
    "spot, then react to, these types of errors using Python’s built-in exception-handling\n",
    "mechanism. If you can spot when an error occurs, you’re then in a position to do\n",
    "something about it.\n",
    "2. Your application is subjected to an at tack\n",
    "Although a case can be made that worrying about attacks on your application\n",
    "is only of concern to web developers, developing practices that improve\n",
    "the robustness of the code you write are always worth considering. With\n",
    "vsearch4web.py, dealing with the “big two” web attack vectors, SQL injection\n",
    "(SQLi) and Cross-site scripting (XSS), appears to be well in hand. This is more of\n",
    "a happy accident than by design on your part, as the Jinja2 library is built to\n",
    "guard against XSS by default, escaping any potentially problematic strings (recall\n",
    "that the JavaScript we tried to trick our webapp into executing had no effect). As\n",
    "regards SQLi, our use of DB-API’s parameterized SQL strings (with all those ?\n",
    "placeholders) ensures—again, thanks to the way these modules were designed—\n",
    "that your code is protected from this entire class of attack.\n",
    "3. Your code take s a long time to e xecute\n",
    "If your code takes a long time to execute, you have to consider the impact on your\n",
    "user’s experience. If your user doesn’t notice, then you’re likely OK. However, if\n",
    "your user has to wait, you may have to do something about it (otherwise, your user\n",
    "may decide the wait isn’t worth it, and go elsewhere).\n",
    "4. Your function call fails\n",
    "It’s not just external systems that generate exceptions in the interpreter—your\n",
    "code can raise exceptions, too. When this happens, you need to be ready to spot\n",
    "the exception, then recover as needed. The mechanism you use to enable this\n",
    "behavior is the same one hinted at in the discussion of issue 1, above.\n",
    "So...where do we start when dealing with these four issues? It’s possible to use the\n",
    "same mechanism to deal with issues 1 and 4, so that’s where we’ll begin.\n",
    "422   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Always Tr y to Execute Error-Prone Code\n",
    "When something goes wrong with your code, Python raises a runtime exception.\n",
    "Think of an exception as a controlled program crash triggered by the interpreter.\n",
    "As you’ve seen with issues 1 and 4, exceptions can be raised under many different\n",
    "circumstances. In fact, the interpreter comes with a whole host of built-in\n",
    "exception types, of which RuntimeError (from issue 4) is only one example.\n",
    "As well as the built-in exception types, it’s possible to define your own custom\n",
    "exceptions, and you’ve seen an example of this too: the InterfaceError\n",
    "exception (from issue 1) is defined by the MySQL Connector module.\n",
    "To spot (and, hopefully, recover from) a runtime exception, deploy Python’s try\n",
    "statement, which can help you manage exceptions as they occur at runtime.\n",
    "For a complete list of the\n",
    "built-in exceptions, see\n",
    "https://docs.python.org/3/\n",
    "library/exceptions.html.\n",
    "To see try in action, let’s first consider a snippet of code that might fail when\n",
    "executed. Here are three innocent-looking, but potentially problematic, lines of\n",
    "code for you to consider:\n",
    "l\n",
    "There’s nothing weird or wonde is rfu\n",
    "file\n",
    "ed\n",
    "nam\n",
    "going on here: the\n",
    "and\n",
    "opened, and its data is obtained\n",
    ".\n",
    "een\n",
    "scr\n",
    "then displayed on\n",
    "There’s nothing wrong with these three lines of code and—as currently written—\n",
    "they will execute. However, this code might fail if it can’t access myfile.txt.\n",
    "Perhaps the file is missing, or your code doesn’t have the necessary file-reading\n",
    "permissions. When the code fails, an exception is raised:\n",
    "When a runtime error\n",
    "occurs, Python displays\n",
    "a “traceback”, which\n",
    "details what went\n",
    "wrong, and where.\n",
    "In this case, the\n",
    "interpreter thinks the\n",
    "problem is on line 2.\n",
    "Whoops!\n",
    "Let’s start learning what try can do by adjusting the above code snippet to\n",
    "protect against this FileNotFoundError exception.\n",
    "Despite being ugly to look\n",
    "at, the traceback message is\n",
    "useful.\n",
    "you are here 4   423"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Catching an Error Is Not Enough\n",
    "When a runtime error occurs, an exception is raised. If you ignore a raised exception\n",
    "it is referred to as uncaught, and the interpreter will terminate your code, then\n",
    "display a runtime error message (as shown in the example from the bottom of the last\n",
    "page). That said, raised exceptions can also be caught (i.e., dealt with) with the try\n",
    "statement. Note that it’s not enough to catch runtime errors, you also have to decide\n",
    "what you’re going to do next.\n",
    "Perhaps you’ll decide to deliberately ignore the raised exception, and keep going...with\n",
    "your fingers firmly crossed. Or maybe you’ll try to run some other code in place of the\n",
    "code that crashed, and keep going. Or perhaps the best thing to do is to log the error\n",
    "before terminating your application as cleanly as possible. Whatever you decide to do,\n",
    "the try statement can help.\n",
    "In its most basic form, the try statement allows you to react whenever the execution\n",
    "of your code results in a raised exception. To protect code with try, put the code\n",
    "within try’s suite. If an exception occurs, the code in the try’s suite terminates, and\n",
    "then the code in the try’s except suite runs. The except suite is where you define\n",
    "what you want to happen next.\n",
    "Let’s update the code snippet from the last page to display a short message whenever\n",
    "the FileNotFoundError exception is raised. The code on the left is what you had\n",
    "previously, while the code on the right has been amended to take advantage of what\n",
    "try and except have to offer:\n",
    "When a runtime\n",
    "error is raised, it\n",
    "can be caught or\n",
    "uncaught: “try”\n",
    "lets you catch a\n",
    "raised error, and\n",
    "“except” lets you\n",
    "do something\n",
    "about it.\n",
    "Note how the entire code\n",
    "snippet is indented under\n",
    "the “try” statement.\n",
    "The “except” statement is\n",
    "indented to the same level\n",
    "as its associated “try”,\n",
    "and has its own suite.\n",
    "Note that what was three lines of code is now six, which may seem wasteful, but isn’t.\n",
    "The original snippet of code still exists as an entity; it makes up the suite associated\n",
    "with the try statement. The except statement and its suite is new code. Let’s see\n",
    "what difference these amendments make.\n",
    "424   Chapter 11\n",
    "This code is indented\n",
    "under the “except” clause\n",
    "and only executes if\n",
    "the “FileNotFoundErr"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Page NO--424"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Test Drive\n",
    "Let’s take the try...except version of your code snippet for a spin. If myfile.txt exists and\n",
    "is readable by your code, its contents will appear on screen. If not, a run-time exception is raised.\n",
    "We already know that myfile.txt does not exist, but now, instead of seeing the ugly traceback\n",
    "message from earlier, the exception-handling code fires and we’re presented with a friendlier\n",
    "message (even though our code snippet still crashed):\n",
    "snippet, the\n",
    "The first time you ran the code tra\n",
    "ack.\n",
    "interpreter generated this ugly ceb\n",
    "The new version of the code produces\n",
    "a much friendlier messages thanks to\n",
    "“try” and “except”.\n",
    "There can be more than one e xception raised...\n",
    "This new behavior is better, but what happens if myfile.txt exists but your\n",
    "code does not have permission to read from it? To see what happens, we created\n",
    "the file, then set its permissions to simulate this eventuality. Rerunning the new\n",
    "code produces this output:\n",
    "Yikes! We’re back to seeing\n",
    "an ugly traceback message,\n",
    "as a “PermissionError” was\n",
    "raised.\n",
    "you are here 4   425"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "tr y Once, but e xcept Many Time s\n",
    "To protect against another exception being raised, simply add another except\n",
    "suite to your try statement, identifying the exception you’re interested in and\n",
    "providing whatever code you deem necessary in the new except’s suite. Here’s\n",
    "another updated version of the code that handles the PermissionError\n",
    "exception (should it be raised):\n",
    "In addition to\n",
    "“FileNotFoundError”\n",
    "exceptions, this code also\n",
    "handles a “PermissionError”.\n",
    "Executing this amended code still results in the PermissionError exception\n",
    "being raised. However, unlike before, the ugly traceback has been replaced by a much\n",
    "friendlier message:\n",
    "This is much better.\n",
    "This is looking good: you’ve managed to adjust what happens whenever the file you’re\n",
    "hoping to work with isn’t there (it doesn’t exist), or is inaccessible (you don’t have the\n",
    "correct permissions). But what happens if an exception is raised that you weren’t\n",
    "expecting?\n",
    "426   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "A Lot of Things Can Go Wrong\n",
    "Before answering the question posed at the bottom of the last page—what happens if\n",
    "an exception is raised that you weren’t expecting?—take a look at some of Python 3’s built-\n",
    "in exceptions (which are copied directly from the Python documentation). Don’t be\n",
    "surprised if you’re struck by just how many there are:\n",
    "All the built-\n",
    "in exceptions\n",
    "inherit from\n",
    "a class called\n",
    "“Exception”.\n",
    "There\n",
    "are an\n",
    "awful lot\n",
    "of these,\n",
    "aren’t\n",
    "there?\n",
    "...\n",
    "Exception\n",
    "+-- StopIteration\n",
    "+-- StopAsyncIteration\n",
    "+-- ArithmeticError\n",
    "|\n",
    "+-- FloatingPointError\n",
    "|\n",
    "+-- OverflowError\n",
    "|\n",
    "+-- ZeroDivisionError\n",
    "+-- AssertionError\n",
    "+-- AttributeError\n",
    "+-- BufferError\n",
    "+-- EOFError\n",
    "+-- ImportError\n",
    "+-- LookupError\n",
    "|\n",
    "+-- IndexError\n",
    "|\n",
    "+-- KeyError\n",
    "+-- MemoryError\n",
    "+-- NameError\n",
    "|\n",
    "+-- UnboundLocalError\n",
    "+-- OSError\n",
    "|\n",
    "+-- BlockingIOError\n",
    "|\n",
    "+-- ChildProcessError\n",
    "|\n",
    "+-- ConnectionError\n",
    "|\n",
    "|\n",
    "+-- BrokenPipeError\n",
    "|\n",
    "|\n",
    "+-- ConnectionAbortedError\n",
    "|\n",
    "|\n",
    "+-- ConnectionRefusedError\n",
    "|\n",
    "|\n",
    "+-- ConnectionResetError\n",
    "|\n",
    "+-- FileExistsError\n",
    "|\n",
    "+-- FileNotFoundError\n",
    "|\n",
    "+-- InterruptedError\n",
    "|\n",
    "+-- IsADirectoryError\n",
    "|\n",
    "+-- NotADirectoryError\n",
    "|\n",
    "+-- PermissionError\n",
    "|\n",
    "+-- ProcessLookupError\n",
    "|\n",
    "+-- TimeoutError\n",
    "\t\t\t...\n",
    "Here’s the two\n",
    "exceptions that our\n",
    "code currently handles.\n",
    "It would be crazy to try to write a separate except suite for each of these runtime\n",
    "exceptions, as some of them may never occur. That said, some might occur, so you\n",
    "do need to worry about them a little bit. Rather than try to handle each exception\n",
    "individually, Python lets you define a catch-all except suite, which fires whenever a\n",
    "runtime exception occurs that you haven’t specifically identified.\n",
    "you are here 4   427"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "The Catch-All Exception Handler\n",
    "Let’s see what happens when some other error occurs. To simulate just such an\n",
    "occurrence, we’ve changed myfile.txt from a file into a folder. Let’s see what\n",
    "happens when we run the code now:\n",
    "Another exception is raised. You could create an extra except suite that fires when\n",
    "this IsADirectoryError exception occurs, but let’s specify a catch-all runtime\n",
    "error instead, which fires whenever any exception (other than the two we’ve already\n",
    "specified) occurs. To do this, add a catch-all except statement to the end of the\n",
    "existing code:\n",
    "This “except”\n",
    "statement\n",
    "is “bare”: it\n",
    "does not refer\n",
    "to a specific\n",
    "exception.\n",
    "Running this amended version of your code gets rid of the ugly traceback, displaying\n",
    "a friendly message instead. No matter what other exception occurs, this code handles it\n",
    "thanks to the addition of the catch-all except statement:\n",
    "428   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Haven’t We Just Lost Some thing?\n",
    "OK. I get what’s going on here. But\n",
    "does this code not now hide the fact that\n",
    "we just had an “IsADirectoryError”? Isn’t\n",
    "it important to know exactly which error\n",
    "you’ve encountered?\n",
    "Ah, yes...good catch.\n",
    "This latest code has tidied up the output (in\n",
    "that the ugly traceback is gone), but you’ve\n",
    "also lost some important information: you no\n",
    "longer know what the specific issue with your\n",
    "code was.\n",
    "Knowing what exception was raised is often\n",
    "important, so Python lets you get at the data\n",
    "associated with the most-recent exception\n",
    "information as it’s being handled. There are two\n",
    "ways to do this: using the facilities of the sys\n",
    "module, and using an extension to the try/\n",
    "except syntax.\n",
    "Let’s look at both of these techniques.\n",
    "Q:\n",
    "A:\n",
    "Is it possible to create a catch-all exception handler that does nothing?\n",
    "Yes. It is often tempting to add this except suite to the bottom of a try statement:\n",
    "\t\texcept:\n",
    "\t\t\n",
    "pass\n",
    "Please try not to do this. This except suite implements a catch-all that ignores any other exception (presumedly in the misguided hope\n",
    "that if something is ignored it might go away). This is a dangerous practice, as—at the very least—an unexpected exception should result in an\n",
    "error message appearing on screen. So, be sure to always write error-checking code that handles exceptions, as opposed to ignores them.\n",
    "you are here 4   429"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Le arning About Exceptions f rom “sys”\n",
    "The standard library comes with a module called sys that provides access to the\n",
    "interpreters, internals (a set of variables and functions available at runtime).\n",
    "One such function is exc_info, which provides information on the exception\n",
    "currently being handled. When invoked, exc_info returns a three-valued\n",
    "tuple where the first value indicates the exception’s type, the second details the\n",
    "exception’s value, and the third contains a traceback object that provides\n",
    "access to the traceback message (should you need it). When there is no currently\n",
    "available exception, exc_info returns the Python null value for each of the\n",
    "tuple values, which looks like this:(None, None, None).\n",
    "Knowing all of this, let’s experiment at the >>> shell. In the IDLE session that\n",
    "follows, we’ve written some code that’s always going to fail (as dividing by zero is\n",
    "never a good idea). A catch-all except suite uses the sys.exc_info function to\n",
    "extract and display data relating to the currently firing exception:\n",
    "To learn more\n",
    "about “sys”, see\n",
    "https://docs.\n",
    "python.org/3/\n",
    "library/sys.html.\n",
    "Be sure to import the “sys” module.\n",
    "Dividing by zero is *never* a good idea...and when your code\n",
    "divides by zero an exception occurs\n",
    "Let’s extract and display the data associated\n",
    "with the currently occurring exception.\n",
    "Here’s the data associated with the\n",
    "exception, which confirms that we\n",
    "have an issue with divide-by-zero.\n",
    "It’s possible to delve deeper into the traceback object to learn more about what\n",
    "just happened, but this already feels like too much work, doesn’t it? All we really\n",
    "want to know is what type of exception occurred.\n",
    "To make this (and your life) easier, Python extends the try/except syntax to\n",
    "make it convenient to get at the information returned by the sys.exc_info\n",
    "function, and it does this without you having to remember to import the sys\n",
    "module, or wrangle with the tuple returned by that function.\n",
    "Recall from a few pages back that the interpreter arranges exceptions in a\n",
    "hierarchy, with each exception inheriting from one called Exception. Let’s take\n",
    "advantage of this hierarchical arrangement as we rewrite our catch-all exception\n",
    "handler.\n",
    "430   Chapter 11\n",
    "Recall the\n",
    "exception hierarchy\n",
    "from earlier.\n",
    "...\n",
    "Exception\n",
    "+--\n",
    "+--\n",
    "+--\n",
    "|\n",
    "|\n",
    "|\n",
    "+--\n",
    "+--\n",
    "+--\n",
    "+--\n",
    "StopIteration\n",
    "StopAsyncIteration\n",
    "ArithmeticError\n",
    "+-- FloatingPointError\n",
    "+-- OverflowError\n",
    "+-- ZeroDivisionError\n",
    "AssertionError\n",
    "AttributeError\n",
    "BufferError"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "The Catch-All Exception Handler, Revisited\n",
    "Consider your current code, which explicitly identifies the two exceptions you\n",
    "want to handle (FileNotFoundError and PermissionError), as well as\n",
    "provides a generic catch-all except suite (to handle everything else):\n",
    "This code works, but\n",
    "doesn’t really tell\n",
    "you much when some\n",
    "unexpected exception\n",
    "occurs.\n",
    "Note how, when referring to a specific exception, we’ve identified the exception by\n",
    "name after the except keyword. As well as identifying specific exceptions after\n",
    "except, it’s also possible to identify classes of exceptions using any of the names\n",
    "in the hierarchy.\n",
    "For instance, if you’re only interested in knowing that an arithmetic error\n",
    "has occurred (as opposed to—specifically—a divide-by-zero error), you\n",
    "could specify except ArithmeticError, which would then catch a\n",
    "FloatingPointError, an OverflowError, and a ZeroDivisionError\n",
    "should they occur. Similarly, if you specify except Exception, you’ll catch\n",
    "any error.\n",
    "But how does this help...surely you’re already catching all errors with a “bare”\n",
    "except statement? It’s true: you are. But you can extend the except\n",
    "Exception statement with the as keyword, which allows you to assign the\n",
    "current exception object to a variable (with err being a very popular name in\n",
    "this situation) and create more informative error message. Take a look at another\n",
    "version of the code, which uses except Exception as:\n",
    "Recall that all the\n",
    "exceptions inherit\n",
    "from “Exception”.\n",
    "...\n",
    "Exception\n",
    "+--\n",
    "+--\n",
    "+--\n",
    "|\n",
    "|\n",
    "|\n",
    "+--\n",
    "+--\n",
    "+--\n",
    "+--\n",
    "StopIteration\n",
    "StopAsyncIteration\n",
    "ArithmeticError\n",
    "+-- FloatingPointError\n",
    "+-- OverflowError\n",
    "+-- ZeroDivisionError\n",
    "AssertionError\n",
    "AttributeError\n",
    "BufferError\n",
    "EOFError\n",
    "...\n",
    "Unlike the “bare” except\n",
    "catch-all shown above, this one\n",
    "arranges for the exception\n",
    "object to be assigned to the\n",
    "“err” variable.\n",
    "The value of “err” is then ly\n",
    "used as part of the friend d\n",
    "message (as it’s always a goo s).\n",
    "idea to report all exception\n",
    "you are here 4   431"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Page No--431"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Test Drive\n",
    "With this—the last of the changes to your try/except code—applied, let’s confirm that everything\n",
    "is working as expected before returning to vsearch4web.py and applying what you now know\n",
    "about exceptions to your webapp.\n",
    "Let’s start with confirming that the code displays the correct message when the file is missing:\n",
    "“myfile.txt”\n",
    "doesn’t exist.\n",
    "If the file exists, but you don’t have permission to access it, a different exception is raised:\n",
    "The file\n",
    "exists, but\n",
    "you can’t\n",
    "read it.\n",
    "Any other exception is handled by the catch-all, which displays a friendly message:\n",
    "Some other\n",
    "exception has\n",
    "occurred. In this\n",
    "case, what you\n",
    "thought was a file\n",
    "is in fact a folder.\n",
    "Finally, if all is OK, the try suite runs without error, and the file’s contents appear on screen:\n",
    "Success! No\n",
    "exceptions\n",
    "occur, so the\n",
    "“try” suite runs\n",
    "to completion.\n",
    "432   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Page No--432"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Ge t ting Back to Our Webapp Code\n",
    "Recall from the start of this chapter that we identified an issue with the call to\n",
    "log_request within vsearch4web.py’s do_search function. Specifically,\n",
    "we’re concerned about what to do when the call to log_request fails:\n",
    "...\n",
    "@app.route('/search4', methods=['POST'])\n",
    "def do_search() -> 'html':\n",
    "phrase = request.form['phrase']\n",
    "letters = request.form['letters']\n",
    "title = 'Here are your results:'\n",
    "results = str(search4letters(phrase, letters))\n",
    "log_request(request, results)\n",
    "return render_template('results.html',\n",
    "the_title=title,\n",
    "the_phrase=phrase,\n",
    "the_letters=letters,\n",
    "the_results=results,)\n",
    "...\n",
    "4. What happens\n",
    "if this call fails?\n",
    "Based on our investigations, we learned that this call might fail if the backend\n",
    "database is unavailable, or if some other error occurs. When an error (of any\n",
    "type) occurs, the webapp responds with an unfriendly error page, which is likely to\n",
    "confuse (rather than enlighten) your webapp’s users:\n",
    "This is not\n",
    "something you\n",
    "want your\n",
    "webapp users\n",
    "to see.\n",
    "Although it is important to us, the logging of each web request is not something\n",
    "that our webapp users really care about; all they want to see is the results of their\n",
    "search. Consequently, let’s adjust the webapp’s code so that it deals with errors\n",
    "within log_request by handling any raised exceptions silently.\n",
    "you are here 4   433"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Page NO--433"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Silently Handling Exceptions\n",
    "Seriously? You’re planning to handle\n",
    "exceptions raised by “log_request” silently?\n",
    "Isn’t that just another variant of ignoring\n",
    "exceptions and hoping they’ll go away?\n",
    "No: “silently” does not mean “ignore.”\n",
    "When we suggest handling exceptions silently in this\n",
    "context, we’re referring to handling any exceptions\n",
    "raised in such a way that your webapp users don’t\n",
    "notice. At the moment, your users do notice, as\n",
    "the webapp crashes with a confusing and—let’s be\n",
    "honest—scary error page.\n",
    "Your webapp users don’t need to worry about\n",
    "log_request failing, but you do. So let’s adjust\n",
    "your code so that exceptions raised by log_\n",
    "request aren’t noticed by your users (i.e., they\n",
    "are silenced), but are noticed by you.\n",
    "Q:\n",
    "A:\n",
    "Doesn’t all this try / except stuff just make my code harder to read and understand?\n",
    "It’s true that the example code in this chapter started out as three easy-to-understand lines of Python code, and then we added seven\n",
    "lines of code, which—on the face of things—have nothing to do with what the first three lines of code are doing. However, it is important to\n",
    "protect code that can potentially raise an exception, and try / except is generally regarded as the best way to do this. Over time, your\n",
    "brain will learn to spot the important stuff (the code actually doing the work) that lives in the try suite, and filter out the except suites that\n",
    "are there to handle exceptions. When trying to understand code that uses try / except , always read the try suite first to learn what the\n",
    "code does, then look at the except suites if you need to understand what happens when things go wrong.\n",
    "434   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Page No--434"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Let’s add some try / except code to do_search ’s invocation of the\n",
    "log_request function. To keep things straightforward, let’s add a catch-\n",
    "all exception handler around the call to log_request , which, when it\n",
    "fires, displays a helpful message on standard output (using a call to the\n",
    "print BIF). In defining a catch-all exception handler, you can suppress\n",
    "your webapp’s standard exception-handling behavior, which currently\n",
    "displays the unfriendly error page.\n",
    "Here’s log_request ’s code as it’s currently written:\n",
    "@app.route('/search4', methods=['POST'])\n",
    "def do_search() -> 'html':\n",
    "phrase = request.form['phrase']\n",
    "letters = request.form['letters']\n",
    "title = 'Here are your results:'\n",
    "results = str(search4letters(phrase, letters))\n",
    "log_request(request, results)\n",
    "return render_template('results.html',\n",
    "the_title=title,\n",
    "the_phrase=phrase,\n",
    "the_letters=letters,\n",
    "the_results=results,)\n",
    "This line of code needs\n",
    "to be protected in\n",
    "case it fails (raising a\n",
    "runtime error).\n",
    "In the spaces below, provide the code that implements a catch-all\n",
    "exception handler around the call to log_request :\n",
    "@app.route('/search4', methods=['POST'])\n",
    "def do_search() -> 'html':\n",
    "phrase = request.form['phrase']\n",
    "letters = request.form['letters']\n",
    "title = 'Here are your results:'\n",
    "results = str(search4letters(phrase, letters))\n",
    "Don’t forget to call\n",
    "“log_request” as part d.\n",
    "of the code you ad\n",
    "return render_template('results.html',\n",
    "the_title=title,\n",
    "the_phrase=phrase,\n",
    "the_letters=letters,\n",
    "the_results=results,)\n",
    "you are here 4   435"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "The plan was to add some try / except code to do_search ’s\n",
    "invocation of the log_request function. To keep things\n",
    "straightforward, we decided to add a catch-all exception handler around\n",
    "the call to log_request , which, when it fires, displays a helpful\n",
    "message on standard output (using a call to the print BIF).\n",
    "Here’s log_request ’s code as currently written:\n",
    "@app.route('/search4', methods=['POST'])\n",
    "def do_search() -> 'html':\n",
    "phrase = request.form['phrase']\n",
    "letters = request.form['letters']\n",
    "title = 'Here are your results:'\n",
    "results = str(search4letters(phrase, letters))\n",
    "log_request(request, results)\n",
    "return render_template('results.html',\n",
    "the_title=title,\n",
    "the_phrase=phrase,\n",
    "the_letters=letters,\n",
    "the_results=results,)\n",
    "In the spaces below, you were to provide the code that implements a\n",
    "catch-all exception handler around the call to log_request :\n",
    "@app.route('/search4', methods=['POST'])\n",
    "def do_search() -> 'html':\n",
    "phrase = request.form['phrase']\n",
    "letters = request.form['letters']\n",
    "title = 'Here are your results:'\n",
    "results = str(search4letters(phrase, letters))\n",
    "This is the\n",
    "catch-all.\n",
    "try:\n",
    "The call to “log_request\n",
    "moved into the suite asso ” is\n",
    "with a new “try” statem ciated\n",
    "ent.\n",
    "log_request(request, results)\n",
    "except Exception as err:\n",
    "print(‘***** Logging failed with this error:’, str(err))\n",
    "return render_template('results.html',\n",
    "the_title=title,\n",
    "the_phrase=phrase,\n",
    "the_letters=letters,\n",
    "the_results=results,)\n",
    "436   Chapter 11\n",
    "s\n",
    "When a runtime error occurs, thi\n",
    "for\n",
    "een\n",
    "scr\n",
    "on\n",
    "message is displayed\n",
    "the admin only. Your user sees\n",
    "nothing."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Page No--"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "(Extended) Test Drive, 1 of 3\n",
    "With the catch-all exception-handling code added to vsearch4web.py, let’s take your webapp for an\n",
    "extended spin (over the next few pages) to see the difference this new code makes. Previously, when\n",
    "something went wrong, your user was greeted with an unfriendly error page. Now, however, the error is\n",
    "handled “silently” by the catch-all code. If you haven’t done so already, run vsearch4web.py, then\n",
    "use any browser to surf to your webapp’s home page:\n",
    "$ python3 vsearch4web.py\n",
    "* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
    "* Restarting with fsevents reloader\n",
    "* Debugger is active!\n",
    "* Debugger pin code: 184-855-980\n",
    "Your webapp is up and runnin\n",
    "waiting to hear fom a browse g, r...\n",
    "Go ahead\n",
    "and surf on\n",
    "over to your\n",
    "webapp’s home\n",
    "page.\n",
    "On the terminal that’s running your code, you should see something like this:\n",
    "...\n",
    "* Debugger\n",
    "127.0.0.1 -\n",
    "127.0.0.1 -\n",
    "127.0.0.1 -\n",
    "pin code: 184-855-980\n",
    "- [14/Jul/2016 10:54:31] \"GET / HTTP/1.1\" 200 -\n",
    "- [14/Jul/2016 10:54:31] \"GET /static/hf.css HTTP/1.1\" 200 -\n",
    "- [14/Jul/2016 10:54:32] \"GET /favicon.ico HTTP/1.1\" 404 -\n",
    "r webapp\n",
    "These 200s confirm that you\n",
    "its\n",
    "g\n",
    "is up and running (and servin s up point.\n",
    "thi\n",
    "home page). All is good at\n",
    "BTW: Don’t worry about this 40\n",
    "4...we haven’t\n",
    "defined a “favicon.ico” file for\n",
    "our\n",
    "(so it gets reported as not found webapp\n",
    "when your\n",
    "browser asks for it).\n",
    "you are here 4   437"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Page NO--437"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "(Extended) Test Drive, 2 of 3\n",
    "In order to simulate an error, we’ve switched off our backend database, which should result in an error\n",
    "occurring whenever the webapp tries to interact with the database. As our code silently catches all errors\n",
    "generated by log_request, the webapp user isn’t aware that the logging hasn’t occurred. The catch-\n",
    "all code has arranged to generate a message on screen describing the problem. Sure enough, when\n",
    "you enter a phrase and click on the “Do it!” button, the webapp displays the results of your search in the\n",
    "browser, whereas the webapp’s terminal screen displays the “silenced” error message. Note that, despite\n",
    "the runtime error, the webapp continues to execute and successfully services the call to /search:\n",
    "...\n",
    "127.0.0.1 - - [14/Jul/2016 10:54:32] \"GET /favicon.ico HTTP/1.1\" 404 -\n",
    "***** Logging failed with this error: 2003: Can't connect to MySQL server on '127.0.0.1:3306'\n",
    "(61 Connection refused)\n",
    "127.0.0.1 - - [14/Jul/2016 10:55:55] \"POST /search4 HTTP/1.1\" 200 -\n",
    "r catch-all\n",
    "This message is generated by e you\n",
    "app user\n",
    "web\n",
    "exception-handling code. Th\n",
    "doesn’t see it.\n",
    "438   Chapter 11\n",
    "Even though an error occurr\n",
    "crash. In other words, the sea ed, rch the webapp didn’t\n",
    "webapp user isn’t aware that the worked (but the\n",
    "logging failed)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Page NO--438"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "(Extended) Test Drive, 3 of 3\n",
    "In fact, no matter what error occurs when log_request runs, the catch-all code handles it.\n",
    "We restarted our backend database, then tried to connect with an incorrect username. You can raise this\n",
    "error by changing the dbconfig dictionary in vsearch4web.py to use vsearchwrong as the\n",
    "value for user:\n",
    "...\n",
    "app.config['dbconfig'] = {'host': '127.0.0.1',\n",
    "'user': 'vsearchwrong',\n",
    "'password': 'vsearchpasswd',\n",
    "'database': 'vsearchlogDB', }\n",
    "....\n",
    "When your webapp reloads and you perform a search, you’ll see a message like this in your terminal:\n",
    "...\n",
    "***** Logging failed with this error: 1045 (28000): Access denied for user 'vsearchwrong'@\n",
    "'localhost' (using password: YES)\n",
    "Change the value for user back to vsearch, and then let’s try to access a nonexistent table,\n",
    "by changing the name of the table in the SQL query used in the log_request function to be\n",
    "logwrong (instead of log):\n",
    "def log_request(req: 'flask_request', res: str) -> None:\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "_SQL = \"\"\"insert into logwrong\n",
    "(phrase, letters, ip, browser_string, results)\n",
    "values\n",
    "(%s, %s, %s, %s, %s)\"\"\"\n",
    "...\n",
    "When your webapp reloads and you perform a search, you’ll see a message like this in your terminal:\n",
    "...\n",
    "***** Logging failed with this error: 1146 (42S02): Table 'vsearchlogdb.logwrong' doesn't exist\n",
    "Change the name of the table back to log and then, as a final example, let’s add a raise statement to\n",
    "the log_request function (just before the with statement), which generates a custom exception:\n",
    "def log_request(req: 'flask_request', res: str) -> None:\n",
    "raise Exception(\"Something awful just happened.\")\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "...\n",
    "When your webapp reloads one last time, and you perform one last search, you’ll see the following\n",
    "message in your terminal:\n",
    "...\n",
    "***** Logging failed with this error: Something awful just happened.\n",
    "you are here 4   439"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Handling Other Database Errors\n",
    "The log_request function makes use of the UseDatabase context manager (as\n",
    "provided by the DBcm module). Now that you’ve protected the call to log_request,\n",
    "you can rest easy, safe in the knowledge that any issues relating to problems with the\n",
    "database will be caught (and handled) by your catch-all exception-handling code.\n",
    "However, the log_request function isn’t the only place where your webapp\n",
    "interacts with the database. The view_the_log function grabs the logging data\n",
    "from the database prior to displaying it on screen.\n",
    "Recall the code for the view_the_log function:\n",
    "...\n",
    "All of this code\n",
    "needs to be\n",
    "protected, too.\n",
    "@app.route('/viewlog')\n",
    "@check_logged_in\n",
    "def view_the_log() -> 'html':\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "_SQL = \"\"\"select phrase, letters, ip, browser_string, results\n",
    "from log\"\"\"\n",
    "cursor.execute(_SQL)\n",
    "contents = cursor.fetchall()\n",
    "titles = ('Phrase', 'Letters', 'Remote_addr', 'User_agent', 'Results')\n",
    "return render_template('viewlog.html',\n",
    "the_title='View Log',\n",
    "the_row_titles=titles,\n",
    "the_data=contents,)\n",
    "...\n",
    "This code can fail, too, as it interacts with the backend database. However, unlike\n",
    "log_request, the view_the_log function is not called from the code in\n",
    "vsearch4web.py; it’s invoked by Flask on your behalf. This means you can’t write\n",
    "code to protect the invocation of view_the_log, as it’s the Flask framework that\n",
    "calls the function, not you.\n",
    "If you can’t protect the invocation of view_the_log, the next best thing is to\n",
    "protect the code in its suite, specifically the use of the UseDatabase context\n",
    "manager. Before considering how to do this, let’s consider what can go wrong:\n",
    "• The backend database may be unavailable.\n",
    "• You may not be able to log in to a working database.\n",
    "• After a successful login, your database query might fail.\n",
    "• Something else (unexpected) might happen.\n",
    "This list of problems is similar to those you had to worry about with log_request.\n",
    "440   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Does “More Errors” Me an “More e xcepts”?\n",
    "Knowing what we now know about try/except, we could add some code to the\n",
    "view_the_log function to protect the use of the UseDatabase context manager:\n",
    "...\n",
    "Another\n",
    "catch-all\n",
    "exception\n",
    "handler\n",
    "@app.route('/viewlog')\n",
    "@check_logged_in\n",
    "def view_the_log() -> 'html':\n",
    "try:\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "\t\t...\n",
    "The rest of\n",
    "the function’s\n",
    "code goes\n",
    "here.\n",
    "except Exception as err:\n",
    "print('Something went wrong:', str(err))\n",
    "This catch-all strategy certainly works (after all, that’s what you used with log_\n",
    "request). However, things can get complicated if you decide to do something other\n",
    "than implement a catch-all exception handler. What if you decide you need to react\n",
    "to a specific database error, such as “Database not found”? Recall from the beginning\n",
    "of this chapter that MySQL reports an InterfaceError exception when this\n",
    "happens:\n",
    "This exception\n",
    "is raised when\n",
    "your code\n",
    "can’t find\n",
    "the backend\n",
    "database.\n",
    "You could add an except statement that targets the InterfaceError exception,\n",
    "but to do this your code also has to import the mysql.connector module, which\n",
    "defines this particular exception.\n",
    "On the face of things, this doesn’t seem like a big deal. But it is.\n",
    "you are here 4   441"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Avoid Tightly Coupled Code\n",
    "Let’s assume you’ve decided to create an except statement that protects against your\n",
    "backend database being unavailable. You could adjust the code in view_the_log to\n",
    "look something like this:\n",
    "...\n",
    "@app.route('/viewlog')\n",
    "@check_logged_in\n",
    "def view_the_log() -> 'html':\n",
    "try:\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "\t\t...\n",
    "The rest of\n",
    "the function’s\n",
    "code still goes\n",
    "in here.\n",
    "except mysql.connector.errors.InterfaceError as err:\n",
    "print('Is your database switched on? Error:', str(err))\n",
    "except Exception as err:\n",
    "print('Something went wrong:', str(err))\n",
    "...\n",
    "If you also remember to add import mysql.connector to the top of your code,\n",
    "this additional except statement works. When your backend database can’t be found,\n",
    "this additional code allows your webapp to remind you to check that your database is\n",
    "switched on.\n",
    "This new code works, and you can see what’s going on here...what’s not to like?\n",
    "The issue with approaching the problem in this way is that the code in\n",
    "vsearch4web.py is now very tightly coupled to the MySQL database, and\n",
    "specifically the use of the MySQL Connector module. Prior to adding this second\n",
    "except statement, your vsearch4web.py code interacted with your backend\n",
    "database via the DBcm module (developed earlier in this book). Specifically, the\n",
    "UseDatabase context manager provides a convenient abstraction that decouples\n",
    "the code in vsearch4web.py from the backend database. If, at some time in the\n",
    "future, you needed to replace MySQL with PostgreSQL, the only changes you’d need\n",
    "to make would be to the DBcm module, not to all the code that uses UseDatabase.\n",
    "However, when you create code like that shown above, you tightly bind (i.e., couple)\n",
    "your webapp code to the MySQL backend database because of that import\n",
    "mysql.connector statement, in addition to your new except statement’s\n",
    "reference to mysql.connector.errors.InterfaceError.\n",
    "If you need to write code that tightly couples to your backend database, always\n",
    "consider putting that code in the DBcm module. This way, your webapp can be written\n",
    "to use the generic interface provided by DBcm, as opposed to a specific interface that\n",
    "targets (and locks you into) a specific backend database.\n",
    "Let’s now consider what moving the above except code into DBcm does for our\n",
    "webapp.\n",
    "442   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "The DBcm Module, Revisited\n",
    "You last looked at DBcm in Chapter 9, when you created that module in order to\n",
    "provide a hook into the with statement when working with a MySQL database. Back\n",
    "then, we sidestepped any discussion of error handling (by conveniently ignoring the\n",
    "issue). Now that you’ve seen what the sys.exc_info function does, you should have\n",
    "a better idea of what the arguments to UseDatabase’s __exit__ method mean:\n",
    "import mysql.connector\n",
    "This is the\n",
    "context\n",
    "manager code\n",
    "in “DBcm.py”.\n",
    "class UseDatabase:\n",
    "def __init__(self, config: dict) -> None:\n",
    "self.configuration = config\n",
    "def __enter__(self) -> 'cursor':\n",
    "self.conn = mysql.connector.connect(**self.configuration)\n",
    "self.cursor = self.conn.cursor()\n",
    "return self.cursor\n",
    "def __exit__(self, exc_type, exc_value, exc_trace) -> None:\n",
    "self.conn.commit()\n",
    "self.cursor.close()\n",
    "Now\n",
    "self.conn.close()\n",
    "Recall that UseDatabase implements three methods:\n",
    "• __init__ provides a configuration opportunity prior to with executing,\n",
    "• __enter__ executes as the with statement starts, and\n",
    "• __exit__ is guaranteed to execute whenever the with’s suite terminates.\n",
    "that you’ve\n",
    "seen “exc_info”,\n",
    "it should be clear\n",
    "what these method\n",
    "arguments refer to:\n",
    "exception data.\n",
    "At least, that’s the expected behavior whenever everything goes to plan. When things\n",
    "go wrong, this behavior changes.\n",
    "For instance, if an exception is raised while __enter__ is executing, the with\n",
    "statement terminates, and any subsequent processing of __exit__ is cancelled. This\n",
    "makes sense: if __enter__ runs into trouble, __exit__ can no longer assume that\n",
    "the execution context is initialized and configured correctly (so it’s prudent not to run\n",
    "the __exit__ method’s code).\n",
    "The big issue with the __enter__ method’s code is that the backend database may\n",
    "not be available, so let’s take some time to adjust __enter__ for this possibility,\n",
    "generating a custom exception when the database connection cannot be established.\n",
    "Once we’ve done this, we’ll adjust view_the_log to check for our custom\n",
    "exception instead of the highly database-specific mysql.connector.errors.\n",
    "InterfaceError.\n",
    "you are here 4   443"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Cre ating Custom Exceptions\n",
    "Creating your own custom exceptions couldn’t be any easier: decide on an appropriate\n",
    "name, then define an empty class that inherits from Python’s built-in Exception\n",
    "class. Once you’ve defined a custom exception, it can be raised with the raise\n",
    "keyword. And once an exception is raised, it’s caught (and dealt with) by try/\n",
    "except.\n",
    "A quick trip to IDLE’s >>> prompt demonstrates custom exceptions in action. In this\n",
    "example, we’re creating a custom exception called ConnectionError, which we\n",
    "then raise (with raise), before catching with try/except. Read the annotations in\n",
    "numbered order, and (if you’re following along) enter the code we’ve typed at the >>>\n",
    "prompt:\n",
    "1. Create a\n",
    "new class called\n",
    "“ConnectionError”\n",
    "that inherits from\n",
    "the “Exception”\n",
    "class.\n",
    "2. “pass” is Python’s empty\n",
    "that creates the empty class. statement\n",
    "3. Raising our new\n",
    "exception (with\n",
    "“raise”) results\n",
    "in a traceback\n",
    "message.\n",
    "4. Catch the\n",
    "“ConnectionError”\n",
    "exception using\n",
    "“try/except”.\n",
    "5. The “ConnectionError” was caught, allowing\n",
    "us to customize the error message.\n",
    "The empt y class isn’t quite empt y...\n",
    "In describing the ConnectionError class as “empty,” we told a little lie.\n",
    "Granted, the use of pass ensures that there’s no new code associated with the\n",
    "ConnectionError class, but the fact that ConnectionError inherits from\n",
    "Python’s built-in Exception class means that all of the attributes and behaviors\n",
    "of Exception are available in ConnectionError too (making it anything but\n",
    "empty). This explains why ConnectionError works just as you’d expect it to with\n",
    "raise and try/except.\n",
    "444   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Let’s adjust the DBcm module to raise a custom ConnectionError\n",
    "whenever a connection to the backend database fails.\n",
    "Here’s the current code to DBcm.py . In the spaces provided, add in the\n",
    "code required to raise a ConnectionError .\n",
    "import mysql.connector\n",
    "class UseDatabase:\n",
    "def __init__(self, config: dict) -> None:\n",
    "self.configuration = config\n",
    "def __enter__(self) -> 'cursor':\n",
    "Add code\n",
    "to “raise” a\n",
    "“ConnnectionError”.\n",
    "self.conn = mysql.connector.connect(**self.configuration)\n",
    "self.cursor = self.conn.cursor()\n",
    "return self.cursor\n",
    "def __exit__(self, exc_type, exc_value, exc_trace) -> None:\n",
    "self.conn.commit()\n",
    "self.cursor.close()\n",
    "self.conn.close()\n",
    "2\n",
    "With the code in the DBcm module amended, use your pencil to detail any\n",
    "changes you’d make to this code from vsearch4web.py in order to\n",
    "take advantage of the newly defined ConnectionError exception:\n",
    "Use your pencil to from DBcm import UseDatabase\n",
    "show the changes import mysql.connector\n",
    "you’d make to this\n",
    "...\n",
    "code now that the\n",
    "the_row_titles=titles,\n",
    "“ConnectionError”\n",
    "exception exists.\n",
    "the_data=contents,)\n",
    "except mysql.connector.errors.InterfaceError as err:\n",
    "print('Is your database switched on? Error:', str(err))\n",
    "except Exception as err:\n",
    "print('Something went wrong:', str(err))\n",
    "return 'Error'\n",
    "you are here 4   445"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ou were to adjust the DBcm module to raise a custom\n",
    "ConnectionError whenever a connection to the backend database\n",
    "fails. You were to adjust the current code to DBcm.py to add in the code\n",
    "required to raise a ConnectionError .\n",
    "1\n",
    "Define the\n",
    "custom exception\n",
    "as an “empty”\n",
    "class that\n",
    "import mysql.connector\n",
    "inherits from\n",
    "class ConnectionError(Exception):\n",
    "“Exception”.\n",
    "pass\n",
    "class UseDatabase:\n",
    "def __init__(self, config: dict) -> None:\n",
    "self.configuration = config\n",
    "def __enter__(self) -> 'cursor':\n",
    "A new “try/\n",
    "except”\n",
    "construct\n",
    "protects the\n",
    "database\n",
    "connection code.\n",
    "try:\n",
    "self.conn = mysql.connector.connect(**self.configuration)\n",
    "self.cursor = self.conn.cursor()\n",
    "return self.cursor\n",
    "except mysql.connector.errors.InterfaceError as err:\n",
    "raise ConnectionError(err)\n",
    "2\n",
    "With the code in the DBcm module amended, you were to detail any\n",
    "changes you’d make to this code from vsearch4web.py in order to\n",
    "take advantage of the newly defined ConnectionError exception:\n",
    "DBcm import UseDatabase ,\n",
    "import mysql.connector\n",
    "...\n",
    "446   Chapter 11\n",
    "Raise the custom\n",
    "exception.\n",
    "def __exit__(self, exc_type, exc_value, exc_trace) -> None:\n",
    "self.conn.commit()\n",
    "self.cursor.close()\n",
    "self.conn.close()\n",
    "You don’t need\n",
    "to import\n",
    "“mysql.connector”\n",
    "anymore (as\n",
    "“DBcm” does\n",
    "this for you). from\n",
    "Change the first\n",
    "“except” statement\n",
    "to look for a\n",
    "“ConnectionError”\n",
    "as opposed to an\n",
    "“InterfaceError”.\n",
    "Within the “DBcm.py” code,\n",
    "refer to the backend\n",
    "database-specific exceptions\n",
    "by their full name.\n",
    "ConnectionError\n",
    "ConnectionError\n",
    "the_row_titles=titles,\n",
    "the_data=contents,)\n",
    "Be sure to\n",
    "import the\n",
    "“ConnectionError”\n",
    "exception from\n",
    "“DBcm”.\n",
    "except mysql.connector.errors.InterfaceError as err:\n",
    "print('Is your database switched on? Error:', str(err))\n",
    "except Exception as err:\n",
    "print('Something went wrong:', str(err))\n",
    "return 'Error'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Test Drive\n",
    "Let’s see what difference this new code makes. Recall that you’ve moved the MySQL-specific\n",
    "exception-handling code from vsearch4web.py into DBcm.py (and replaced it with code that\n",
    "looks for your custom ConnectionError exception). Has this made any difference?\n",
    "Here are the messages that the previous version of vsearch4web.py generated whenever the\n",
    "backend database couldn’t be found:\n",
    "...\n",
    "Is your database switched on? Error: 2003: Can't connect to MySQL server on '127.0.0.1:3306'\n",
    "(61 Connection refused)\n",
    "127.0.0.1 - - [16/Jul/2016 21:21:51] \"GET /viewlog HTTP/1.1\" 200 -\n",
    "And here are the messages that the most recent version of vsearch4web.py generates whenever\n",
    "the backend database can’t be found:\n",
    "...\n",
    "Is your database switched on? Error: 2003: Can't connect to MySQL server on '127.0.0.1:3306'\n",
    "(61 Connection refused)\n",
    "127.0.0.1 - - [16/Jul/2016 21:22:58] \"GET /viewlog HTTP/1.1\" 200 -\n",
    "You’re trying to\n",
    "trick me, aren’t you?\n",
    "These error messages\n",
    "are the same!\n",
    "Yes. On the face of things, these are the same.\n",
    "However, although the output from the current and previous\n",
    "versions of vsearch4web.py appears identical, behind the\n",
    "scenes things are very different.\n",
    "If you decide to change the backend database from MySQL to\n",
    "PostgreSQL, you no longer have to worry about changing any\n",
    "of the code in vsearch4web.py, as all of your database-\n",
    "specific code resides in DBcm.py. As long as the changes you\n",
    "make to DBcm.py maintain the same interface as previous\n",
    "versions of the module, you can change SQL databases as\n",
    "often as you like. This may not seem like a big deal now, but if\n",
    "vsearch4web.py grows to hundreds, thousands, or tens of\n",
    "thousands of lines of code, its really is a big deal.\n",
    "you are here 4   447"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "What Else Can Go Wrong with “DBcm”?\n",
    "Even if your backend database is up and running, things can still go wrong.\n",
    "For example, the credentials used to access the database may be incorrect. If\n",
    "they are, the __enter__ method will fail again, this time with a mysql.\n",
    "connector.errors.ProgrammingError.\n",
    "Or, the suite of code associated with your UseDatabase context manager\n",
    "may raise an exception, as there’s never a guarantee that it executes correctly. A\n",
    "mysql.connector.errors.ProgrammingError is also raised whenever\n",
    "your database query (the SQL you’re executing) contains an error.\n",
    "The error message associated with an SQL query error is different than the\n",
    "message associated with the credentials error, but the exception raised is the same:\n",
    "mysql.connector.errors.ProgrammingError. Unlike with credentials\n",
    "errors, errors in your SQL results in an exception being raised while the with\n",
    "statement is executing. This means that you’ll need to consider protecting against\n",
    "this exception in more than one place. The question is: where?\n",
    "To answer this question, let’s take another look at DBcm’s code:\n",
    "import mysql.connector\n",
    "class ConnectionError(Exception):\n",
    "pass\n",
    "class UseDatabase:\n",
    "def __init__(self, config: dict):\n",
    "self.configuration = config\n",
    "This code\n",
    "can raise a\n",
    "“ProgrammingError”\n",
    "exception.\n",
    "def __enter__(self) -> 'cursor':\n",
    "try:\n",
    "self.conn = mysql.connector.connect(**self.configuration)\n",
    "self.cursor = self.conn.cursor()\n",
    "return self.cursor\n",
    "except mysql.connector.errors.InterfaceError as err:\n",
    "raise ConnectionError(err)\n",
    "def __exit__(self, exc_type, exc_value, exc_traceback):\n",
    "self.conn.commit()\n",
    "self.cursor.close()\n",
    "self.conn.close()\n",
    "ur\n",
    "But what about exceptions that occ\n",
    "pen\n",
    "hap\n",
    "se\n",
    "The\n",
    "e?\n",
    "suit\n",
    "within the “with”\n",
    "ends\n",
    "*after* the “__enter__” method\n",
    "but *before* the “__exit__” method\n",
    "starts.\n",
    "448   Chapter 11\n",
    "You might be tempted to suggest that exceptions raised within the\n",
    "with suite should be handled with a try/except statement\n",
    "within the with, but such a strategy gets you right back to writing\n",
    "tightly coupled code. But consider this: when an exception is\n",
    "raised within with’s suite and not caught, the with statement\n",
    "arranges to pass details of the uncaught exception into your\n",
    "context manager’s __exit__ method, where you have the\n",
    "option of doing something about it."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Cre ating More Custom Exceptions\n",
    "Let’s extend DBcm.py to report two additional, custom exceptions.\n",
    "The first is called CredentialsError and is raised when a ProgrammingError\n",
    "occurs within the __enter__ method. The second is called SQLError and is raised\n",
    "when a ProgrammingError is reported to the __exit__ method.\n",
    "Defining these new exceptions is easy: add two new, empty exception classes to the top\n",
    "of DBcm.py:\n",
    "import mysql.connector\n",
    "class ConnectionError(Exception):\n",
    "pass\n",
    "class CredentialsError(Exception):\n",
    "pass\n",
    "class SQLError(Exception):\n",
    "pass\n",
    "Two additional\n",
    "classes define your\n",
    "two new exceptions.\n",
    "class UseDatabase:\n",
    "def __init__(self, configuration: dict):\n",
    "self.config = configuration\n",
    "\t\t...\n",
    "A CredentialsError can occur during __enter__, so let’s adjust that method’s\n",
    "code to reflect this. Recall that an incorrect MySQL username or password results in a\n",
    "ProgrammingError being raised:\n",
    "\t\t...\n",
    "try:\n",
    "self.conn = mysql.connector.connect(**self.config)\n",
    "Add this code to\n",
    "self.cursor = self.conn.cursor()\n",
    "the “__enter__”\n",
    "return self.cursor\n",
    "l\n",
    "dea\n",
    "to\n",
    "d\n",
    "metho\n",
    "except\n",
    "mysql.connector.errors.InterfaceError as err:\n",
    "es.\n",
    "issu\n",
    "in\n",
    "log\n",
    "with any\n",
    "raise ConnectionError(err)\n",
    "except mysql.connector.errors.ProgrammingError as err:\n",
    "raise CredentialsError(err)\n",
    "def __exit__(self, exc_type, exc_value, exc_traceback):\n",
    "self.conn.commit()\n",
    "self.cursor.close()\n",
    "self.conn.close()\n",
    "These code changes adjust DBcm.py to raise a CredentialsError exception\n",
    "when you provide either an incorrect username or password from your code to your\n",
    "backend database (MySQL). Adjusting vsearch4web.py’s code is your next task.\n",
    "you are here 4   449"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Are Your Database Credentials Correct?\n",
    "With these latest changes made to DBcm.py, let’s now adjust the code in\n",
    "vsearch4web.py, paying particular attention to the view_the_log function.\n",
    "However, before doing anything else, add CredentialsError to the list of\n",
    "imports from DBcm at the top of your vsearch4web.py code:\n",
    "Be sure to\n",
    "import your\n",
    "new exception.\n",
    "...\n",
    "from DBcm import UseDatabase, ConnectionError, CredentialsError\n",
    "...\n",
    "With the import line amended, you next need to add a new except\n",
    "suite to the view_the_log function. As when you added support for a\n",
    "ConnectionError, this is a straightforward edit:\n",
    "@app.route('/viewlog')\n",
    "@check_logged_in\n",
    "def view_the_log() -> 'html':\n",
    "try:\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "_SQL = \"\"\"select phrase, letters, ip, browser_string, results\n",
    "from log\"\"\"\n",
    "cursor.execute(_SQL)\n",
    "contents = cursor.fetchall()\n",
    "titles = ('Phrase', 'Letters', 'Remote_addr', 'User_agent', 'Results')\n",
    "return render_template('viewlog.html',\n",
    "the_title='View Log',\n",
    "the_row_titles=titles,\n",
    "the_data=contents,)\n",
    "except ConnectionError as err:\n",
    "print('Is your database switched on? Error:', str(err))\n",
    "except CredentialsError as err:\n",
    "print('User-id/Password issues. Error:', str(err))\n",
    "except Exception as err:\n",
    "print('Something went wrong:', str(err))\n",
    "return 'Error'\n",
    "There’s really nothing new here, as all you’re doing is repeating what you did\n",
    "for ConnectionError. Sure enough, if you try to connect to your backend\n",
    "database with an incorrect username (or password), your webapp now displays an\n",
    "appropriate message, like this:\n",
    "”\n",
    "Add this code to “view_the_ s log\n",
    "use\n",
    "e\n",
    "to catch when your cod\n",
    "the wrong username or password\n",
    "with MySQL.\n",
    "...\n",
    "User-id/Password issues. Error: 1045 (28000): Access denied for user 'vsearcherror'@'localhost'\n",
    "(using password: YES)\n",
    "127.0.0.1 - - [25/Jul/2016 16:29:37] \"GET /viewlog HTTP/1.1\" 200 -\n",
    "450   Chapter 11\n",
    "Now that your code knows all about\n",
    "“CredentialsError”, you generate an exception-\n",
    "specific error message."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Handling SQLError Is Dif ferent\n",
    "Both ConnectionError and CredentialsError are raised due to\n",
    "problems with the __enter__ method’s code executing. When either exception\n",
    "is raised, the corresponding with statement’s suite is not executed.\n",
    "If all is well, your with suite executes as normal.\n",
    "Recall this with statement from the log_request function, which uses the\n",
    "UseDatabase context manager (provided by DBcm) to insert data into the\n",
    "backend database:\n",
    "We need to worry\n",
    "about what happens\n",
    "if something goes\n",
    "wrong with this\n",
    "code )i.e., the code\n",
    "within the “with”\n",
    "suite).\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "_SQL = \"\"\"insert into log\n",
    "(phrase, letters, ip, browser_string, results)\n",
    "values\n",
    "(%s, %s, %s, %s, %s)\"\"\"\n",
    "cursor.execute(_SQL, (req.form['phrase'],\n",
    "req.form['letters'],\n",
    "req.remote_addr,\n",
    "req.user_agent.browser,\n",
    "res, ))\n",
    "If (for some reason) your SQL query contains an error, the MySQL Connector\n",
    "module generates a ProgrammingError, just like the one raised during your\n",
    "context manager’s __enter__ method. However, as this exception occurs within\n",
    "your context manager (i.e., within the with statement) and is not caught there, the\n",
    "exception is passed back to the __exit__ method as three arguments: the type\n",
    "of the exception, the value of the exception, and the traceback associated with the\n",
    "exception.\n",
    "If you take a quick look at DBcm’s existing code for __exit__, you’ll see that the\n",
    "three arguments are ready and waiting to be used:\n",
    "The three\n",
    "exception\n",
    "arguments are\n",
    "ready for use.\n",
    "def __exit__(self, exc_type, exc_value, exc_traceback):\n",
    "self.conn.commit()\n",
    "self.cursor.close()\n",
    "self.conn.close()\n",
    "When an exception is raised within the with suite and not caught, the context\n",
    "manager terminates the with suite’s code, and jumps to the __exit__\n",
    "method, which then executes. Knowing this, you can write code that checks for\n",
    "exceptions of interest to your application. However, if no exception is raised, the\n",
    "three arguments (exc_type, exc_value, and exc_traceback) are all set to\n",
    "None. Otherwise, they are populated with details of the raised exception.\n",
    "Let’s exploit this behavior to raise an SQLError whenever something goes wrong\n",
    "within the UseDatabase context manager’s with suite.\n",
    "“None” is\n",
    "Python’s\n",
    "null value.\n",
    "you are here 4   451"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Be Careful with Code Positioning\n",
    "To check whether an uncaught exception has occurred within your code’s with\n",
    "statement, check the exc_type argument to the __exit__ method within __\n",
    "exit__’s suite, being careful to consider exactly where you add your new code.\n",
    "You’re not about to tell me that it\n",
    "makes a difference where I put my\n",
    "“exc_type” checking code, are you?\n",
    "Yes, it does make a difference.\n",
    "To understand why, consider that your context\n",
    "manager’s __exit__ method provides a place\n",
    "where you can put code that is guaranteed to\n",
    "execute after your with suite ends. That behavior is\n",
    "part of the context manager protocol, after all.\n",
    "This behavior needs to hold even when exceptions\n",
    "are raised within your context manager’s with\n",
    "suite. Which means that if you plan to add code\n",
    "to the __exit__ method, it’s best to put it after\n",
    "any existing code in __exit__, as that way you’ll\n",
    "still guarantee the method’s existing code executes\n",
    "(and preserve the semantics of the context manager\n",
    "protocol).\n",
    "Let’s take another look at the existing code in the __exit__ method in light of\n",
    "this code placement discussion. Consider that any code we add needs to raise an\n",
    "SQLError exception if exc_type indicates a ProgrammingError has occurred:\n",
    "If you add code in here,\n",
    "and that code raises\n",
    "an exception, the three\n",
    "existing lines of code\n",
    "won’t be executed.\n",
    "452   Chapter 11\n",
    "def __exit__(self, exc_type, exc_value, exc_traceback):\n",
    "self.conn.commit()\n",
    "self.cursor.close()\n",
    "self.conn.close()\n",
    "Adding code *after* the ee\n",
    "existing lines\n",
    "of code ensures “__exit__” thr\n",
    "doe\n",
    "s\n",
    "*before* any passed-in except its thing\n",
    "ion is dealt\n",
    "with."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Raising an SQLError\n",
    "At this stage, you’ve already added the SQLError exception class to the top of the\n",
    "DBcm.py file:\n",
    "import mysql.connector\n",
    "class ConnectionError(Exception):\n",
    "pass\n",
    "class CredentialsError(Exception):\n",
    "pass\n",
    "class SQLError(Exception):\n",
    "pass\n",
    "Here’s where\n",
    "you added in\n",
    "the “SQLError”\n",
    "exception.\n",
    "class UseDatabase:\n",
    "def __init__(self, config: dict):\n",
    "self.configuration = config\n",
    "\t\t...\n",
    "With the SQLError exception class defined, all you need to do now is add some\n",
    "code to the __exit__ method to check whether exc_type is the exception you’re\n",
    "interested in, and if it is, raise an SQLError. This is so straightforward that\n",
    "we are resisting the usual Head First urge to turn creating the required code into an\n",
    "exercise, as no one wants to insult anyone’s intelligence at this stage in this book. So,\n",
    "here’s the code you need to append to the __exit__ method:\n",
    "If a “ProgrammingError”\n",
    "occurs, raise an\n",
    "“SQLError”.\n",
    "def __exit__(self, exc_type, exc_value, exc_traceback):\n",
    "self.conn.commit()\n",
    "self.cursor.close()\n",
    "self.conn.close()\n",
    "if exc_type is mysql.connector.errors.ProgrammingError:\n",
    "raise SQLError(exc_value)\n",
    "If you want to be extra safe, and do something sensible with any other, unexpected\n",
    "exception sent to __exit__, you can add an elif suite to the end of the\n",
    "__exit__ method that reraises the unexpected exception to the calling code:\n",
    "\t\t...\n",
    "self.conn.close()\n",
    "if exc_type is mysql.connector.errors.ProgrammingError:\n",
    "raise SQLError(exc_value)\n",
    "This “elif” raises\n",
    "elif exc_type:\n",
    "any other exception\n",
    "raise exc_type(exc_value)\n",
    "that might occur.\n",
    "you are here 4   453"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Test Drive\n",
    "With support for the SQLError exception added to DBcm.py, add another except suite to your\n",
    "view_the_log function to catch any SQLErrors that occur:\n",
    "Add this code\n",
    "into the “view_\n",
    "the_log” function\n",
    "within your\n",
    "“vsearch4web.py”\n",
    "webapp.\n",
    "\t\t...\n",
    "except ConnectionError as err:\n",
    "print('Is your database switched on? Error:', str(err))\n",
    "except CredentialsError as err:\n",
    "print('User-id/Password issues. Error:', str(err))\n",
    "except SQLError as err:\n",
    "print('Is your query correct? Error:', str(err))\n",
    "except Exception as err:\n",
    "print('Something went wrong:', str(err))\n",
    "return 'Error'\n",
    "Once you save vsearch4web.py, your webapp should reload and be ready for testing. If you try\n",
    "to execute an SQL query that contains errors, the exception is handled by the above code:\n",
    "...\n",
    "Is your query correct? Error: 1146 (42S02): Table 'vsearchlogdb.logerror' doesn't exist\n",
    "127.0.0.1 - - [25/Jul/2016 21:38:25] \"GET /viewlog HTTP/1.1\" 200 -\n",
    "No more generic “ProgrammingError” exceptions from code\n",
    "MySQL Connector, as your custom exception-handling\n",
    "catches these errors now.\n",
    "Equally, if something unexpected happens, your webapp’s catch-all code kicks into gear, displaying\n",
    "an appropriate message:\n",
    "...\n",
    "Something went wrong: Some unknown exception.\n",
    "127.0.0.1 - - [25/Jul/2016 21:43:14] \"GET /viewlog HTTP/1.1\" 200 -\n",
    "If something unexpected\n",
    "happens, your code\n",
    "handles it.\n",
    "With exception-handling code added to your webapp, no matter what runtime error occurs, your\n",
    "webapp continues to function without displaying a scary or confusing error page to your users.\n",
    "And the really nice thing about\n",
    "this is that this code takes the generic\n",
    "“ProgrammingError” exception provided by\n",
    "the MySQL Connector module and turns\n",
    "it into two custom exceptions that have\n",
    "specific meaning for our webapp.\n",
    "Yes, it does. And this is very powerful.\n",
    "454   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "A Quick Recap: Adding Robustne ss\n",
    "Let’s take a minute to remind ourselves of what we set out to do in this chapter.\n",
    "In attempting to make our webapp code more robust, we had to answer four\n",
    "questions relating to four identified issues. Let’s review each question and note\n",
    "how we did:\n",
    "1 What happens if the database connection fails?\n",
    "You created a new exception called ConnectionError that is raised whenever\n",
    "your backend database can’t be found. You then used try/except to handle a\n",
    "ConnectionError were it to occur.\n",
    "2 Is our webapp protected from web attacks?\n",
    "It was a “happy accident,” but your choice of Flask plus Jinja2, together with Python’s\n",
    "DB-API specification, protects your webapp from the most notorious of web attacks. So,\n",
    "yes, your webapp is protected from some web attacks (but not all).\n",
    "3 What happens if something takes a long time?\n",
    "We still haven’t answered this question, other than to demonstrate what happens when\n",
    "your webapp takes 15 seconds to respond to a user request: your web user has to wait (or,\n",
    "more likely, your web user gets fed up waiting and leaves).\n",
    "4 What happens if a function call fails?\n",
    "You used try/except to protect the function call, which allowed you to control what\n",
    "the user of your webapp sees when something goes wrong.\n",
    "What happens if some thing takes a long time?\n",
    "When you did the initial exercise at the start of this chapter, this question resulted\n",
    "from our examination of the cursor.execute calls that occurred in the\n",
    "log_request and view_the_log functions. Although you’ve already worked\n",
    "with both of these functions in answering questions 1 and 4, above, you’re not\n",
    "done with them quite yet.\n",
    "Both log_request and view_the_log use the UseDatabase context\n",
    "manager to execute an SQL query. The log_request function writes the\n",
    "details of the submitted search to the backend database, whereas the view_\n",
    "the_log function reads from the database.\n",
    "The question is: what do you do if this write or read takes a long time?\n",
    "Well, as with a lot of things in the programming world, it depends.\n",
    "you are here 4   455"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "How to De al with Wait? It Depends...\n",
    "How you decide to deal with code that makes your users wait—either on a read, or\n",
    "on a write—can get complex. So we’re going to pause this discussion and defer a\n",
    "solution until the next, short chapter.\n",
    "In fact, the next chapter is so short that it doesn’t warrant its own chapter number\n",
    "(as you’ll see), but the material it presents is complex enough to justify splitting it\n",
    "off from this chapter’s main discussion, which presented Python’s try/except\n",
    "mechanism. So, let’s hang on for a bit before putting to rest issue 3: what happens if\n",
    "something takes a long time?\n",
    "You do realize you’re\n",
    "asking us to wait to deal\n",
    "with code that waits?\n",
    "Yes. The irony is not lost on us.\n",
    "We’re asking you to wait to learn how to\n",
    "handle “waits” in your code.\n",
    "But you’ve already learned a lot in this\n",
    "chapter, and we think it’s important to\n",
    "take a bit of time to let the try/except\n",
    "material sink into your brain.\n",
    "So, we’d like you to pause, and take a short\n",
    "break...after you’ve cast your eye over the\n",
    "code seen thus far in this chapter.\n",
    "456   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Chapter 11’s Code, 1 of 3\n",
    "try:\n",
    "This is “try_example.py”.\n",
    "with open('myfile.txt') as fh:\n",
    "file_data = fh.read()\n",
    "print(file_data)\n",
    "except FileNotFoundError:\n",
    "print('The data file is missing.')\n",
    "except PermissionError:\n",
    "print('This is not allowed.')\n",
    "except Exception as err:\n",
    "print('Some other error occurred:', str(err))\n",
    "import mysql.connector\n",
    "class ConnectionError(Exception):\n",
    "pass\n",
    "class CredentialsError(Exception):\n",
    "pass\n",
    "class SQLError(Exception):\n",
    "pass\n",
    "class UseDatabase:\n",
    "def __init__(self, config: dict):\n",
    "self.configuration = config\n",
    "def __enter__(self) -> 'cursor':\n",
    "try:\n",
    "self.conn = mysql.connector.connect(**self.configuration)\n",
    "self.cursor = self.conn.cursor()\n",
    "return self.cursor\n",
    "except mysql.connector.errors.InterfaceError as err:\n",
    "raise ConnectionError(err)\n",
    "except mysql.connector.errors.ProgrammingError as err:\n",
    "raise CredentialsError(err)\n",
    "This is the\n",
    "exception-\n",
    "savvy\n",
    "version of\n",
    "“DBcm.py”.\n",
    "def __exit__(self, exc_type, exc_value, exc_traceback):\n",
    "self.conn.commit()\n",
    "self.cursor.close()\n",
    "self.conn.close()\n",
    "if exc_type is mysql.connector.errors.ProgrammingError:\n",
    "raise SQLError(exc_value)\n",
    "elif exc_type:\n",
    "raise exc_type(exc_value)\n",
    "you are here 4   457"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Chapter 11’s Code, 2 of 3\n",
    "This is the version of “vsearch4\n",
    "that makes your users wait... web.py”\n",
    "from flask import Flask, render_template, request, escape, session\n",
    "from flask import copy_current_request_context\n",
    "from vsearch import search4letters\n",
    "from DBcm import UseDatabase, ConnectionError, CredentialsError, SQLError\n",
    "from checker import check_logged_in\n",
    "from time import sleep\n",
    "app = Flask(__name__)\n",
    "app.config['dbconfig'] = {'host': '127.0.0.1',\n",
    "'user': 'vsearch',\n",
    "'password': 'vsearchpasswd',\n",
    "'database': 'vsearchlogDB', }\n",
    "@app.route('/login')\n",
    "def do_login() -> str:\n",
    "session['logged_in'] = True\n",
    "return 'You are now logged in.'\n",
    "@app.route('/logout')\n",
    "def do_logout() -> str:\n",
    "session.pop('logged_in')\n",
    "return 'You are now logged out.'\n",
    "It’s probably a good idea to ent\n",
    "protect this “with” statem\n",
    "in much the same way as\n",
    "you protected the “with” ”\n",
    "statement in “view_the_log\n",
    "(on the next page).\n",
    "@app.route('/search4', methods=['POST'])\n",
    "def do_search() -> 'html':\n",
    "@copy_current_request_context\n",
    "def log_request(req: 'flask_request', res: str) -> None:\n",
    "sleep(15) # This makes log_request really slow...\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "_SQL = \"\"\"insert into log\n",
    "(phrase, letters, ip, browser_string, results)\n",
    "values\n",
    "(%s, %s, %s, %s, %s)\"\"\"\n",
    "cursor.execute(_SQL, (req.form['phrase'],\n",
    "req.form['letters'],\n",
    "req.remote_addr,\n",
    "req.user_agent.browser,\n",
    "res, ))\n",
    "phrase = request.form['phrase']\n",
    "letters = request.form['letters']\n",
    "title = 'Here are your results:'\n",
    "458   Chapter 11"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "Chapter 11’s Code, 3 of 3\n",
    "results = str(search4letters(phrase, letters))\n",
    "try:\n",
    "log_request(request, results))\n",
    "except Exception as err:\n",
    "print('***** Logging failed with this error:', str(err))\n",
    "return render_template('results.html',\n",
    "the_title=title,\n",
    "the_phrase=phrase,\n",
    "the_letters=letters,\n",
    "This is\n",
    "the_results=results,)\n",
    "the\n",
    "rest of the\n",
    "“do_search”\n",
    "function.\n",
    "@app.route('/')\n",
    "@app.route('/entry')\n",
    "def entry_page() -> 'html':\n",
    "return render_template('entry.html',\n",
    "the_title='Welcome to search4letters on the web!')\n",
    "@app.route('/viewlog')\n",
    "@check_logged_in\n",
    "def view_the_log() -> 'html':\n",
    "try:\n",
    "with UseDatabase(app.config['dbconfig']) as cursor:\n",
    "_SQL = \"\"\"select phrase, letters, ip, browser_string, results\n",
    "from log\"\"\"\n",
    "cursor.execute(_SQL)\n",
    "contents = cursor.fetchall()\n",
    "# raise Exception(\"Some unknown exception.\")\n",
    "titles = ('Phrase', 'Letters', 'Remote_addr', 'User_agent', 'Results')\n",
    "return render_template('viewlog.html',\n",
    "the_title='View Log',\n",
    "the_row_titles=titles,\n",
    "the_data=contents,)\n",
    "except ConnectionError as err:\n",
    "print('Is your database switched on? Error:', str(err))\n",
    "except CredentialsError as err:\n",
    "print('User-id/Password issues. Error:', str(err))\n",
    "except SQLError as err:\n",
    "print('Is your query correct? Error:', str(err))\n",
    "except Exception as err:\n",
    "print('Something went wrong:', str(err))\n",
    "return 'Error'\n",
    "app.secret_key = 'YouWillNeverGuessMySecretKey'\n",
    "if __name__ == '__main__':\n",
    "app.run(debug=True)\n",
    "you are here 4   459"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
